/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#define LED_PIN 14
/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/
void SysClock_init(void);
int main(void)
{
	SysClock_init();
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;

	GPIOB->MODER |= 1U << GPIO_MODER_MODER14_Pos; // general output B14
	GPIOB->OTYPER &= ~GPIO_OTYPER_OT14_Msk; //clean
	GPIOB->OTYPER |= 0U << GPIO_OTYPER_OT14_Pos; // unnecessary?

	while(1){
		GPIOB->ODR |= GPIO_ODR_ODR_14;
		for (int i=0;i<500000;i++);
		GPIOB->ODR &= ~GPIO_ODR_ODR_14;
		for (int i=0;i<500000;i++);
	}
}

void SysClock_init(void){
	//HSE ON
	RCC->CR |= RCC_CR_HSEON;
	while (!(RCC->CR & RCC_CR_HSERDY)); //block until HSE rdy

	//FLASH
	FLASH->ACR |= FLASH_ACR_PRFTEN | FLASH_ACR_LATENCY_5WS;

	// APB1, APB2, AHB prescaler
	RCC->CFGR |= RCC_CFGR_HPRE_DIV1 | RCC_CFGR_PPRE1_DIV4 | RCC_CFGR_PPRE2_DIV2;

	// CONFIGURE PLL
	// turn on
	RCC->PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSE; // PLL source MUX
	RCC->PLLCFGR &= ~(RCC_PLLCFGR_PLLM_Msk); // clean PLLM
	RCC->PLLCFGR |= (4U << RCC_PLLCFGR_PLLM_Pos); //PLLM, div factor
	RCC->PLLCFGR &= ~(RCC_PLLCFGR_PLLN_Msk); // clean PLLN
	RCC->PLLCFGR |= (168U << RCC_PLLCFGR_PLLN_Pos); // PLLN, mul factor for VCO
	RCC->PLLCFGR |= (0U << RCC_PLLCFGR_PLLP_Pos); //PLLP 00=2
	RCC->PLLCFGR |= (7U << RCC_PLLCFGR_PLLQ_Pos); //PLLQ
	RCC->PLLCFGR |= (2U << RCC_PLLCFGR_PLLR_Pos); //PLLR

	// turn on PLL
	RCC->CR |= RCC_CR_PLLON;
	while (!(RCC->CR & RCC_CR_PLLRDY)); //block until PLL rdy

	// SYSTEM MUX source = PLLCLK connect
	RCC->CFGR |= RCC_CFGR_SW_PLL;
	while(!(RCC->CFGR & RCC_CFGR_SWS_PLL));



}
